### ISSUE TITLE
Add loading spinner

### ISSUE THREAD

**Issue by bwellington** [axismaps/pilotplan#39]

**Comment by davidheyman** [comment]
2 issues:

1. I wasn’t able to get the loading screen to go away. I was only testing locally so this could be where the issue is, but it’s worth another check and perhaps adding in a failsafe to remove it after no longer than 5 seconds.

2. Can you have it appear only after a use has closed the intro / era screen? I’d like people to still be able to read that content while waiting for it to load.

**Comment by davidheyman** [comment]
Update on my first issue: The loading screen removes itself fine when there is a URL parameter that changes the map starting position. Without one, it stays on indefinitely.

**Comment by bwellington** [comment]
Updated--I always forget to test without URL parameters. Do you still think it needs a 5 second fail-safe timer? It might be strange to be released into the map when it's still not loaded. On an unrelated note, I kind of like that you can see the map loading behind the spinner. At least it is obvious that something is happening.
