### ISSUE TITLE
Select features don't span tile boundaries

### ISSUE THREAD

**Issue by davidheyman** [axismaps/pilotplan#41]
Clicking on a feature from the list retrieved by click probe or search doesn't draw beyond a tile boundary.

<img width="783" alt="2018-10-04_15-54-43" src="https://user-images.githubusercontent.com/791434/46482861-54951380-c7ee-11e8-8c97-caa0f5cdc926.png">

If the tile boundaries are going to be drawn for these features, we'll want to implement the Turf.js union we put off on an earlier issue.

**Comment by bwellington** [comment]
I think this is because click and area searches are just grabbing rendered features within certain boundaries. I'll need to try to search all source features for each click/area result and render these features (possibly after turf.js union). But no matter what we'll never be able to highlight anything beyond the currently loaded tiles (unless we try to first zoom out to the feature extents, wait for data to load, then highlight)

**Comment by davidheyman** [comment]
Instead of zooming all the way out, I think it should work if you make it an iterative process:

1. Search all visible tiles for features matching the selected feature name
2. When a matching feature is found, union it into the selected feature
3. Adjust the zoom to accommodate the larger feature (with a small amount of padding)
4. If the zoom adjustment caused new tiles to load, repeat the process and keep going until no new features are found

**Comment by bwellington** [comment]
I'll give it a try. This could potentially be a long process if the user selects a large feature when zoomed in.

**Comment by bwellington** [comment]
Revised--working better but not perfect

**Comment by davidheyman** [comment]
This is working exactly how it should!

I did get it to crash once, but haven't been able to repeat it. I'll make a note of where the error is if it happens again.
