### ISSUE TITLE
Searching map returns features in fragments

### ISSUE THREAD

**Issue by bwellington** [axismaps/pilotplan#6]
Search features are often returned in fragments, causes them to show up multiple times in the sidebar and highlight only partially on the map. Maybe this is something that needs to be fixed on the back-end? I could also try to dynamically merge features after searching. Or we could build our own geojson API.

**Comment by davidheyman** [comment]
When you say returned in fragments, do you mean that different parts of the same feature (with the same name)  are returned separately? This is a quirk of the data. Parts of the same feature are stored as separate features because they have different dates. For example, if the first part of a road was build in 1950, it would have dates from 1950 - 8888. If the second part of the road was built in 1960, its dates would be 1960 - 8888.

Because of this, we can't join these features together before the data is uploaded. Instead, I would recommend replicating the functionality of the old API. When search results are returned, group them by name and join their ID's into an array. Then, update your draw / highlight function to take an array of IDs and draw all of them together.

**Comment by bwellington** [comment]
Yeah, I'm doing something similar for layer highlighting. The only issue is it doesn't look great when contiguous polygons are rendered in component parts:
![polygons](https://user-images.githubusercontent.com/11998214/45569793-a91c2300-b82e-11e8-9ced-92344d506945.png)
I could use something like http://turfjs.org/docs#union to merge polygons before rendering, if it matters.

**Comment by davidheyman** [comment]
Don't worry about dissolving the polygons for now.
